---
- name: Install Cockpit packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ cockpit_packages }}"

- name: Enable Cockpit Socket
  service:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Enable Cockpit on Firewalld
  firewalld:
    service: cockpit
    state: enabled
    permanent: yes
