---
## Also set the individual system hostname with `ansible_set_hostname` on the inventory per DNS host
system_domain: kemo.labs
## dns_systems must match the values set for `ansible_set_hostname` on the inventory
dns_systems:
  - name: dns-core-1
    ip: 192.168.42.2
  - name: dns-core-2
    ip: 192.168.42.3

upstream_dns_servers:
  - 192.168.42.4

knot_auth_dns_forward_resolver_fallback: false
knot_auth_dns_forward_resolver_fallback_servers:
  - remote_name: pihole
    dnsproxy_id: default
    address: 192.168.42.4
    port: 53

knot_resolver_forward_domains:
  - name: satelliteLabs
    zone: satellite.kemo.labs
    destination: 192.168.50.10
    port: 53

default_zone_soa_params:
  refresh: 6h
  retry: 1h
  expire: 1w
  min_ttl: 600

extra_resolver_acls:
  - name: openshift4
    subnetCIDR: 10.0.0.0/8
    # mode corresponds to kresd policy modes: PASS, DENY, DROP, REFUSE
    mode: PASS
  - name: openshift4SDN
    subnetCIDR: 172.16.0.0/12
    # mode corresponds to kresd policy modes: PASS, DENY, DROP, REFUSE
    mode: PASS
  - name: allKemoLabs
    subnetCIDR: 192.168.0.0/16
    # mode corresponds to kresd policy modes: PASS, DENY, DROP, REFUSE
    mode: PASS

generate_reverse_zones: true

cleanup_old_zone_backups: true
cleanup_old_zone_backups_older_than: 30d

zones:
  - name: kemo.labs
    subnet: 192.168.42.0/24
    subnet_v6: fdf4:e2e0:df12:a100::/64
    reverse_dns_base: 42.168.192.in-addr.arpa
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs
      A:
        - name: dns-core-1
          ttl: 6400
          value: 192.168.42.2
        - name: dns-core-2
          ttl: 6400
          value: 192.168.42.3

        - name: unifi
          ttl: 6400
          value: 192.168.42.1

        - name: freeipa
          ttl: 6400
          value: 192.168.42.7

        - name: freeipa-ca
          ttl: 6400
          value: 192.168.42.7

        - name: keycloak
          ttl: 6400
          value: 192.168.42.8

        - name: ca
          ttl: 6400
          value: 192.168.42.9

        - name: dns-pihole
          ttl: 6400
          value: 192.168.42.4

        - name: deluge
          ttl: 6400
          value: 192.168.42.24

        - name: winnas-pc
          ttl: 6400
          value: 192.168.42.25

        - name: thebus
          ttl: 6400
          value: 192.168.42.30

        - name: gitlab
          ttl: 6400
          value: 192.168.42.31

        - name: vpn
          value: 192.168.42.38
          ttl: 6400

        - name: rhvm
          value: 192.168.42.39
          ttl: 6400

        - name: rhv1
          value: 192.168.42.40
          ttl: 6400
        #        - name: rhv1-nic-2
        #          value: 192.168.42.41
        #          ttl: 6400
        #        - name: rhv1-nic-3
        #          value: 192.168.42.42
        #          ttl: 6400
        #        - name: rhv1-nic-4
        #          value: 192.168.42.43
        #          ttl: 6400

        - name: rhv2
          value: 192.168.42.45
          ttl: 6400
        #        - name: rhv2-nic-2
        #          value: 192.168.42.46
        #          ttl: 6400
        #        - name: rhv2-nic-3
        #          value: 192.168.42.47
        #          ttl: 6400
        #        - name: rhv2-nic-4
        #          value: 192.168.42.47
        #          ttl: 6400

        - name: vcenter
          ttl: 6400
          value: 192.168.42.60

        - name: ansible-tower
          ttl: 6400
          value: 192.168.42.62

        - name: compendium
          ttl: 6400
          value: 192.168.42.63

        - name: satellite
          ttl: 6400
          value: 192.168.42.69

        - name: api.ocp4
          ttl: 6400
          value: 192.168.42.70

        - name: apps.ocp4
          ttl: 6400
          value: 192.168.42.71

        - name: "*.apps.ocp4"
          ttl: 6400
          value: 192.168.42.71

      AAAA:
        - name: dns-core-1
          ttl: 6400
          value: fdf4:e2e0:df12:a100::20
        - name: dns-core-2
          ttl: 6400
          value: fdf4:e2e0:df12:a100::21
        - name: dns-pihole
          ttl: 6400
          value: fdf4:e2e0:df12:a100::54c

        - name: unifi
          ttl: 6400
          value: fdf4:e2e0:df12:a100::0

        - name: thebus
          ttl: 6400
          value: fdf4:e2e0:df12:a100::30

        - name: freeipa
          ttl: 6400
          value: fdf4:e2e0:df12:a100::22

        - name: freeipa-ca
          ttl: 6400
          value: fdf4:e2e0:df12:a100::22

        - name: keycloak
          ttl: 6400
          value: fdf4:e2e0:df12:a100::23

        - name: ca
          ttl: 6400
          value: fdf4:e2e0:df12:a100::9

        - name: gitlab
          value: fdf4:e2e0:df12:a100::31
          ttl: 6400

        - name: vpn
          value: fdf4:e2e0:df12:a100::38
          ttl: 6400

        - name: rhvm
          value: fdf4:e2e0:df12:a100::39
          ttl: 6400

        - name: rhv1
          value: fdf4:e2e0:df12:a100::40
          ttl: 6400
        #        - name: rhv1-nic-2
        #          value: fdf4:e2e0:df12:a100::41
        #          ttl: 6400
        #        - name: rhv1-nic-3
        #          value: fdf4:e2e0:df12:a100::42
        #          ttl: 6400
        #        - name: rhv1-nic-4
        #          value: fdf4:e2e0:df12:a100::43
        #          ttl: 6400

        - name: rhv2
          value: fdf4:e2e0:df12:a100::45
          ttl: 6400
        #        - name: rhv2-nic-2
        #          value: fdf4:e2e0:df12:a100::46
        #          ttl: 6400
        #        - name: rhv2-nic-3
        #          value: fdf4:e2e0:df12:a100::47
        #          ttl: 6400
        #        - name: rhv2-nic-4
        #          value: fdf4:e2e0:df12:a100::48
        #          ttl: 6400

        - name: ansible-tower
          ttl: 6400
          value: fdf4:e2e0:df12:a100::62

        - name: compendium
          ttl: 6400
          value: fdf4:e2e0:df12:a100::63

        - name: satellite
          ttl: 6400
          value: fdf4:e2e0:df12:a100::69

        - name: api.ocp4
          ttl: 6400
          value: fdf4:e2e0:df12:a100::70

        - name: apps.ocp4
          ttl: 6400
          value: fdf4:e2e0:df12:a100::71

        - name: "*.apps.ocp4"
          ttl: 6400
          value: fdf4:e2e0:df12:a100::71

      TXT:
        - name: _kerberos
          ttl: 6400
          value: "KEMO.LABS"

      SRV:
        - name: _kerberos._udp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100
        - name: _kerberos._tcp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100

        - name: _kerberos-master._udp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100
        - name: _kerberos-master._tcp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100

        - name: _kpasswd._udp
          value: freeipa.kemo.labs
          port: 464
          priority: 0
          ttl: 6400
          weight: 100
        - name: _kpasswd._tcp
          value: freeipa.kemo.labs
          port: 464
          priority: 0
          ttl: 6400
          weight: 100

        - name: _ldap._tcp
          value: freeipa.kemo.labs
          port: 389
          priority: 0
          ttl: 6400
          weight: 100
        - name: _ldaps._tcp
          value: freeipa.kemo.labs
          port: 636
          priority: 0
          ttl: 6400
          weight: 100

        - name: _ntp._udp
          value: freeipa.kemo.labs
          port: 123
          priority: 0
          ttl: 6400
          weight: 100

  - name: wireless.kemo.labs
    subnet: 192.168.40.0/24
    subnet_v6: fdf4:e2e0:df12:a140::/64
    reverse_dns_base: 40.168.192.in-addr.arpa
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

  - name: guests.kemo.labs
    subnet: 192.168.38.0/24
    subnet_v6: fdf4:e2e0:df12:a138::/64
    reverse_dns_base: 38.168.192.in-addr.arpa
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

  - name: internet.of.shit.kemo.labs
    subnet: 192.168.36.0/24
    subnet_v6: fdf4:e2e0:df12:a136::/64
    reverse_dns_base: 36.168.192.in-addr.arpa
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

  - name: san.kemo.labs
    subnet: 192.168.44.0/24
    subnet_v6: fdf4:e2e0:df12:a144::/64
    reverse_dns_base: 44.168.192.in-addr.arpa
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

      A:
        - name: thebus
          ttl: 6400
          value: 192.168.44.30
        - name: rhvm
          ttl: 6400
          value: 192.168.44.39
        - name: rhv1
          ttl: 6400
          value: 192.168.44.40
        #        - name: rhv1-10g-1
        #          ttl: 6400
        #          value: 192.168.44.40
        #        - name: rhv1-10g-2
        #          ttl: 6400
        #          value: 192.168.44.41

        - name: rhv2
          ttl: 6400
          value: 192.168.44.45
        #        - name: rhv2-10g-1
        #          ttl: 6400
        #          value: 192.168.44.45
        #        - name: rhv2-10g-2
        #          ttl: 6400
        #          value: 192.168.44.46

        - name: compendium
          ttl: 6400
          value: 192.168.44.63

      AAAA:
        - name: thebus
          ttl: 6400
          value: fdf4:e2e0:df12:a144::30

        - name: rhvm
          ttl: 6400
          value: fdf4:e2e0:df12:a144::39

        - name: rhv1
          ttl: 6400
          value: fdf4:e2e0:df12:a144::40
        #        - name: rhv1-10g-1
        #          ttl: 6400
        #          value: fdf4:e2e0:df12:a144::40
        #        - name: rhv1-10g-2
        #          ttl: 6400
        #          value: fdf4:e2e0:df12:a144::41

        - name: rhv2
          ttl: 6400
          value: fdf4:e2e0:df12:a144::45
        #        - name: rhv2-10g-1
        #          ttl: 6400
        #          value: fdf4:e2e0:df12:a144::45
        #        - name: rhv2-10g-2
        #          ttl: 6400
        #          value: fdf4:e2e0:df12:a144::46

        - name: compendium
          ttl: 6400
          value: fdf4:e2e0:df12:a144::63

  - name: mgmt.kemo.labs
    subnet: 192.168.46.0/24
    subnet_v6: fdf4:e2e0:df12:a146::/64
    reverse_dns_base: 46.168.192.in-addr.arpa
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs
      A:
        - name: thebus
          value: 192.168.46.30
          ttl: 6400
        - name: rhv1
          value: 192.168.46.40
          ttl: 6400
        - name: rhv2
          value: 192.168.46.45
          ttl: 6400
        - name: rhv3
          value: 192.168.46.50
          ttl: 6400
      AAAA:
        - name: thebus
          ttl: 6400
          value: fdf4:e2e0:df12:a146::30
        - name: rhv1
          ttl: 6400
          value: fdf4:e2e0:df12:a146::40
        - name: rhv2
          ttl: 6400
          value: fdf4:e2e0:df12:a146::45
        - name: rhv3
          ttl: 6400
          value: fdf4:e2e0:df12:a146::50

  - name: satellite.kemo.labs
    subnet: 192.168.50.0/24
    subnet_v6: fdf4:e2e0:df12:a150::/64
    reverse_dns_base: 50.168.192.in-addr.arpa
    ttl: 3600

  - name: rh.kemo.labs
    subnet: 192.168.69.0/24
    subnet_v6: fdf4:e2e0:df12:a169::/64
    reverse_dns_base: 69.168.192.in-addr.arpa
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

      A:
        - name: rhv1
          ttl: 6400
          value: 192.168.69.40
        - name: rhv2
          ttl: 6400
          value: 192.168.69.50
        - name: rhv3
          ttl: 6400
          value: 192.168.69.60

        - name: api.ocp4
          ttl: 6400
          value: 192.168.69.70
        - name: apps.ocp4
          ttl: 6400
          value: 192.168.69.71
        - name: "*.apps.ocp4"
          ttl: 6400
          value: 192.168.69.71

      AAAA:
        - name: rhv1
          ttl: 6400
          value: fdf4:e2e0:df12:a169::40
        - name: rhv2
          ttl: 6400
          value: fdf4:e2e0:df12:a169::50
        - name: rhv3
          ttl: 6400
          value: fdf4:e2e0:df12:a169::60
        - name: api.ocp4
          ttl: 6400
          value: fdf4:e2e0:df12:a169::70
        - name: apps.ocp4
          ttl: 6400
          value: fdf4:e2e0:df12:a169::71
        - name: "*.apps.ocp4"
          ttl: 6400
          value: fdf4:e2e0:df12:a169::71
  #  - name: kemo.network
  #    subnet: 192.168.0.0/16
  #    reverse_dns_base: 211.71.71.in-addr.arpa
  #    ttl: 3600
  #    records:
  #      NS:
  #        - name: dns-core-1
  #          ttl: 86400
  #          domain: kemo.labs
  #        - name: dns-core-2
  #          ttl: 86400
  #          domain: kemo.labs
  #      A:
  #        - name: api.ocp4
  #          ttl: 6400
  #          value: 192.168.42.73
  #
  #        - name: apps.ocp4
  #          ttl: 6400
  #          value: 192.168.42.74
  #
  #        - name: "*.apps.ocp4"
  #          ttl: 6400
  #          value: 192.168.42.74
# example zone config
## Assumes two authoritative dns servers at dns-core-1.example.com and dns-core-2.example.com serving both zones
#zones:
#  - name: example.com
#    subnet: 192.168.42.0/24
#    subnet_v6: fdf4:e2e0:df12:a100::/64
#    reverse_dns_base: 42.168.192.in-addr.arpa
#    ttl: 3600
#    records:
#      NS:
#        - name: dns-core-1
#          ttl: 86400
#          domain: kemo.labs
#        - name: dns-core-2
#          ttl: 86400
#          domain: kemo.labs
#      A:
#        - name: dns-core-1
#          ttl: 86400
#          value: 192.168.42.2
#        - name: dns-core-2
#          ttl: 86400
#          value: 192.168.42.3
#        - name: idm
#          type: A
#          ttl: 86400
#          value: 192.168.42.10
#
#      AAAA:
#        - name: dns-core-1
#          ttl: 86400
#          value: 2001:DB8::2
#        - name: dns-core-2
#          ttl: 86400
#          value: 2001:DB8::3
#
#      CNAME:
#        - name: dns2
#          ttl: 6400
#          value: dns-core-2.example.com
#
#      MX:
#        - name: '@'
#          ttl: 3600
#          priority: 1
#          value: ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 5
#          value: ALT1.ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 5
#          value: ALT2.ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 10
#          value: ALT3.ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 10
#          value: ALT4.ASPMX.L.GOOGLE.COM
#
#      TXT:
#        - name: '@'
#          ttl: 6400
#          value: "v=spf1 includespf.dynect.net ~all"
#
#      SRV:
#        - name: _ntp._udp
#          value: idm.example.com
#          port: 123
#          priority: 0
#          ttl: 6400
#          weight: 100
#
#  - name: example.net
#    subnet: 192.168.42.0/24
#    ttl: 3600
#    records:
#      NS:
#        - name: dns-core-1
#          ttl: 86400
#          domain: example.com
#        - name: dns-core-2
#          ttl: 86400
#          domain: example.com
#      A:
#        - name: '@'
#          ttl: 3600
#          value: 192.168.42.100
#        - name: www
#          ttl: 3600
#          value: 192.168.42.100
