---
## Also set the individual system hostname with `ansible_set_hostname` on the inventory per DNS host
system_domain: kemo.labs
## dns_systems must match the values set for `ansible_set_hostname` on the inventory
dns_systems:
  - name: dns-core-1
    ip: 192.168.42.2
  - name: dns-core-2
    ip: 192.168.42.3

upstream_dns_servers:
  - 192.168.42.4

knot_auth_dns_forward_resolver_fallback: false
knot_auth_dns_forward_resolver_fallback_servers:
  - remote_name: pihole
    dnsproxy_id: default
    address: 192.168.42.4
    port: 53

default_zone_soa_params:
  refresh: 6h
  retry: 1h
  expire: 1w
  min_ttl: 600

zones:
  - name: kemo.labs
    subnet: 192.168.42.0/24
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs
      A:
        - name: dns-core-1
          ttl: 6400
          value: 192.168.42.2
        - name: dns-core-2
          ttl: 6400
          value: 192.168.42.3

        - name: unifi
          ttl: 6400
          value: 192.168.42.1

        - name: freeipa
          ttl: 6400
          value: 192.168.42.7

        - name: freeipa-ca
          ttl: 6400
          value: 192.168.42.7

        - name: keycloak
          ttl: 6400
          value: 192.168.42.8

        - name: dns-pihole
          ttl: 6400
          value: 192.168.42.4

        - name: thebus
          ttl: 6400
          value: 192.168.42.30

        - name: vcenter
          ttl: 6400
          value: 192.168.42.60

        - name: ansible-tower
          ttl: 6400
          value: 192.168.42.62

      AAAA:
        - name: dns-core-1
          ttl: 6400
          value: fdf4:e2e0:df12:a100::20
        - name: dns-core-2
          ttl: 6400
          value: fdf4:e2e0:df12:a100::21
        - name: dns-pihole
          ttl: 6400
          value: fdf4:e2e0:df12:a100::54c

        - name: unifi
          ttl: 6400
          value: fdf4:e2e0:df12:a100::0

        - name: thebus
          ttl: 6400
          value: fdf4:e2e0:df12:a100::30

        - name: freeipa
          ttl: 6400
          value: fdf4:e2e0:df12:a100::22

        - name: freeipa-ca
          ttl: 6400
          value: fdf4:e2e0:df12:a100::22

        - name: keycloak
          ttl: 6400
          value: fdf4:e2e0:df12:a100::23

        - name: ansible-tower
          ttl: 6400
          value: fdf4:e2e0:df12:a100::62

      TXT:
        - name: _kerberos
          ttl: 6400
          value: "KEMO.LABS"

      SRV:
        - name: _kerberos._udp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100
        - name: _kerberos._tcp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100

        - name: _kerberos-master._udp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100
        - name: _kerberos-master._tcp
          value: freeipa.kemo.labs
          port: 88
          priority: 0
          ttl: 6400
          weight: 100

        - name: _kpasswd._udp
          value: freeipa.kemo.labs
          port: 464
          priority: 0
          ttl: 6400
          weight: 100
        - name: _kpasswd._tcp
          value: freeipa.kemo.labs
          port: 464
          priority: 0
          ttl: 6400
          weight: 100

        - name: _ldap._tcp
          value: freeipa.kemo.labs
          port: 389
          priority: 0
          ttl: 6400
          weight: 100
        - name: _ldaps._tcp
          value: freeipa.kemo.labs
          port: 636
          priority: 0
          ttl: 6400
          weight: 100

        - name: _ntp._udp
          value: freeipa.kemo.labs
          port: 123
          priority: 0
          ttl: 6400
          weight: 100

  - name: wireless.kemo.labs
    subnet: 192.168.40.0/24
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

  - name: guests.kemo.labs
    subnet: 192.168.38.0/24
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

  - name: internet.of.shit.kemo.labs
    subnet: 192.168.36.0/24
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

  - name: san.kemo.labs
    subnet: 192.168.44.0/24
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs

      A:
        - name: compendium
          ttl: 6400
          value: 192.168.44.63

      AAAA:
        - name: compendium
          ttl: 6400
          value: fdf4:e2e0:df12:a144::63

  - name: mgmt.kemo.labs
    subnet: 192.168.46.0/24
    ttl: 3600
    records:
      NS:
        - name: dns-core-1
          ttl: 86400
          domain: kemo.labs
        - name: dns-core-2
          ttl: 86400
          domain: kemo.labs
      A:
        - name: thebus
          value: 192.168.46.30
          ttl: 86400
# example zone config
## Assumes two authoritative dns servers at dns-core-1.example.com and dns-core-2.example.com serving both zones
#zones:
#  - name: example.com
#    subnet: 192.168.42.0/24
#    ttl: 3600
#    records:
#      NS:
#        - name: dns-core-1
#          ttl: 86400
#          domain: kemo.labs
#        - name: dns-core-2
#          ttl: 86400
#          domain: kemo.labs
#      A:
#        - name: dns-core-1
#          ttl: 86400
#          value: 192.168.42.2
#        - name: dns-core-2
#          ttl: 86400
#          value: 192.168.42.3
#        - name: idm
#          type: A
#          ttl: 86400
#          value: 192.168.42.10
#
#      AAAA:
#        - name: dns-core-1
#          ttl: 86400
#          value: 2001:DB8::2
#        - name: dns-core-2
#          ttl: 86400
#          value: 2001:DB8::3
#
#      CNAME:
#        - name: dns2
#          ttl: 6400
#          value: dns-core-2.example.com
#
#      MX:
#        - name: '@'
#          ttl: 3600
#          priority: 1
#          value: ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 5
#          value: ALT1.ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 5
#          value: ALT2.ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 10
#          value: ALT3.ASPMX.L.GOOGLE.COM
#        - name: '@'
#          ttl: 3600
#          priority: 10
#          value: ALT4.ASPMX.L.GOOGLE.COM
#
#      TXT:
#        - name: '@'
#          ttl: 6400
#          value: "v=spf1 includespf.dynect.net ~all"
#
#      SRV:
#        - name: _ntp._udp
#          value: idm.example.com
#          port: 123
#          priority: 0
#          ttl: 6400
#          weight: 100
#
#  - name: example.net
#    subnet: 192.168.42.0/24
#    ttl: 3600
#    records:
#      NS:
#        - name: dns-core-1
#          ttl: 86400
#          domain: example.com
#        - name: dns-core-2
#          ttl: 86400
#          domain: example.com
#      A:
#        - name: '@'
#          ttl: 3600
#          value: 192.168.42.100
#        - name: www
#          ttl: 3600
#          value: 192.168.42.100
