---
- name: Configure CentOS/RHEL System as DNS Core Server with dnsmasq
  hosts: dns_servers
  become: yes

  tasks:
    - name: Include Default variables
      include_vars: defaults/main.yaml

    - name: Include Global variables
      include_vars: vars/main.yaml

    - name: Include DNS Config variables
      include_vars: vars/dns_config.yaml

    - name: System Updater
      include_tasks: tasks/update_system.yaml
      when: update_system_packages|bool

    - name: Install base packages
      include_tasks: tasks/install_base_packages.yaml

    - name: Set up Firewalld
      include_tasks: tasks/setup_firewalld.yaml

    - name: Set up dnsmasq
      include_tasks: tasks/setup_dnsmasq.yaml

    - name: Set up Cockpit
      include_tasks: tasks/setup_cockpit.yaml
      when: setup_cockpit|bool

  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted
