---
- name: Create local generated files directory
  file:
    path: "{{ ansibleWorkingDirectory }}/vmware-automation"
    state: directory
    mode: "0755"

- name: Download VMWare SSL File
  get_url:
    url: "https://{{ vcenter_server }}/certs/download.zip"
    dest: "{{ ansibleWorkingDirectory }}/vmware-automation/cabundle.zip"

- name: Unpack CA file bundle
  unarchive:
    src: "{{ ansibleWorkingDirectory }}/vmware-automation/cabundle.zip"
    dest: "{{ ansibleWorkingDirectory }}/vmware-automation/"

- name: Move CA file to appropriate location
  copy:
    src: "{{ ansibleWorkingDirectory }}/vmware-automation/certs/lin/*"
    dest: /etc/pki/ca-trust/source/anchors/

- name: Update local CA keystore
  shell: update-ca-trust

- name: Install VMWare Automation SDK via pip
  pip:
    name: git+https://github.com/vmware/vsphere-automation-sdk-python.git
    state: latest
