---
- name: Enable Firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Enable Ports on Firewalld
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  with_items: "{{ firewalld_ports }}"
  notify: reload firewalld

- name: Enable Services on Firewalld
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
  with_items: "{{ firewalld_services }}"
  notify: reload firewalld
