---
- name: Install Knot Resolver Repo
  yum:
    name: https://secure.nic.cz/files/knot-resolver/knot-resolver-release.el.rpm
    state: latest

- name: Install Knot Resolver
  yum:
    name: ["knot-resolver", "knot-utils"]
    state: latest
    update_cache: yes
