---
- name: Create VMs in VMWare
  hosts: localhost
  connection: local

  gather_facts: true
  vars_files:
    - defaults/main.yaml
    - vars/vcenter_password.yaml
    - vars/vcenter_vars.yaml

  pre_tasks:
    - name: Set up local environment
      include_role:
        name: ../roles/localVMWareSetup
      tags:
        - vmwareSetup

  tasks:
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ new_vm_name }}"
        template: "{{ template_name }}"
        datacenter: "{{ vcenter_datacenter_name }}"
        folder: "{{ vcenter_folder }}"
        state: "{{ new_vm_state }}"
        cluster: "{{ vcenter_cluster_name }}"
        wait_for_ip_address: yes
